nhour/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from . import views

urlpatterns = [
    url(r'^login', login, name='login'),
    url(r'^delete/([0-9]*)/$', views.delete_entry, name='delete_entry'),
    url(r'^edit/([0-9]{4})/([0-9]{1,2})/([0-9]*)/$', views.edit_week, name='edit_week'),
    url(r'^save/([0-9]*)/$', views.save_entry, name="save_entry"),
    url(r'^create/$', views.create_entry, name="create_entry"),
    url(r'^$', views.index_redirect),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^register/$', views.register, name="register"),
    url(r'^admin/', admin.site.urls),
    url(r'^thanks/', views.thank_you, name="thanks"),
    url(r'^complete/([0-9]{4})/([0-9]{1,2})/([0-9]*)/$', views.week_complete, name="complete")
]

nhour_base/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from nhour import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/', include('nhour.urls'))
]

nhour/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import CharField, TextField, DateField, DateTimeField, ForeignKey, DecimalField, EmailField, \
    ManyToManyField, BooleanField
from django.db.models.fields import IntegerField


class System(models.Model):
    name = CharField(max_length=100)
    description = TextField(max_length=700, blank=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = CharField(max_length=100)
    description = TextField(max_length=600, blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = CharField(max_length=100)
    description = TextField(max_length=600, blank=True)
    related_systems = ManyToManyField(System)

    def __str__(self):
        return self.name


class CompletedWeek(models.Model):
    week = IntegerField(validators=[MaxValueValidator(53),
                                    MinValueValidator(1)])
    year = IntegerField(validators=[MaxValueValidator(9999),
                                    MinValueValidator(1000)])
    user = ForeignKey(User, on_delete=models.PROTECT)


class Entry(models.Model):
    week = IntegerField(validators=[MaxValueValidator(52),
                                    MinValueValidator(1)])
    year = IntegerField(validators=[MaxValueValidator(9999),
                                    MinValueValidator(1000)])
    hours = DecimalField(decimal_places=2,
                         max_digits=5,
                         validators=[MaxValueValidator(100),
                                     MinValueValidator(0)])
    user = ForeignKey(User, on_delete=models.PROTECT)
    comment = TextField(max_length=5000, blank=True, null=True)

    class Meta:
        ordering = ("-year", "-week")


class RegularEntry(Entry):
    system = ForeignKey('System', on_delete=models.PROTECT)
    project = ForeignKey(
        'Project', on_delete=models.PROTECT,
        null=True, blank=True)
    task = ForeignKey('Task', on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Regular Entries"

    def __eq__(self, other):
        return isinstance(other, Entry) and other.id == self.id

    @staticmethod
    def get_entries_of_week(user, year, week):
        return RegularEntry.objects.filter(year=year, week=week, user=user)



class Activity(models.Model):
    name = CharField(max_length=100)
    description = TextField(max_length=600, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Activities"


class SpecialEntry(Entry):
    activity = ForeignKey('Activity', on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Special Entries"

    @staticmethod
    def get_entries_of_week(user, year, week):
        return SpecialEntry.objects.filter(year=year, week=week, user=user)

nhour/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form

from nhour.models import RegularEntry, System, Project, Task, SpecialEntry, Activity, Entry


class EntryForm(ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}), required=False)

    class Meta:
        fields = ['user', 'week', 'year', 'hours', 'comment']
        widgets = {'user': forms.HiddenInput(),
                   'week': forms.HiddenInput(),
                   'year': forms.HiddenInput(),
                   'hours': forms.HiddenInput()}


class RegularEntryForm(EntryForm):
    system = forms.ModelChoiceField(System.objects.all().order_by('name'), empty_label="Select a system")
    project = forms.ModelChoiceField(Project.objects.all().order_by('name'), empty_label="Select a project", required=False)
    task = forms.ModelChoiceField(Task.objects.all().order_by('name'), empty_label="Select a task")
    class Meta(EntryForm.Meta):
        model = RegularEntry
        fields = ['system', 'project', 'task'] + EntryForm.Meta.fields


class SpecialEntryForm(EntryForm):
    activity = forms.ModelChoiceField(Activity.objects.all().order_by('name'), empty_label="Select an activity")
    class Meta(EntryForm.Meta):
        model = SpecialEntry
        fields = ["activity"] + EntryForm.Meta.fields


def entry_form_factory(instance: Entry, *args, **kwargs) -> EntryForm:

    if type(instance) == Entry:
        if hasattr(instance, "regularentry"):
            return RegularEntryForm(instance=instance.regularentry, *args, **kwargs)
        elif hasattr(instance, "specialentry"):
            return SpecialEntryForm(instance=instance.specialentry, *args, **kwargs)

    elif type(instance) == SpecialEntry:
        return SpecialEntryForm(instance=instance, *args, **kwargs)
    else:
        return RegularEntryForm(instance=instance, *args, **kwargs)


class RegisterForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), validators=[validate_password])
    password_again = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True, min_length=2)
    last_name = forms.CharField(required=True, min_length=2)
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super(ModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean_password_again(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password_again")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                "The passwords didn't match!",
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password_again'), self.instance)
        return password2

nhour/views.py
import datetime

from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db.models import Sum
from django.forms import Form
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from nhour.forms import RegularEntryForm, RegisterForm, entry_form_factory, SpecialEntryForm
from nhour.models import SpecialEntry, RegularEntry, Entry, System, Task, Project, Activity, CompletedWeek
from nhour.utils import entry_shortcuts, unfinished_weeks_of_user, correct_week_overflow


@login_required()
def index_redirect(request):
    unfinished_weeks = unfinished_weeks_of_user(request.user)
    if unfinished_weeks:
        oldest_unfinished_week_year, oldest_unfinished_week = sorted(
            unfinished_weeks)[0]
        return edit_week(request, oldest_unfinished_week_year,
                         oldest_unfinished_week, request.user.id)
    else:
        today = datetime.datetime.today()
        return edit_week(request, today.year, today.isocalendar()[1],
                         request.user.id)


def register(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            new_user = register_form.save(commit=False)
            new_user.is_active = False
            new_user.save()
            return redirect("thanks")
    else:
        register_form = RegisterForm()
    return render(request,
                  "registration/register.html",
                  context={'register_form': register_form})


def thank_you(request):
    return render(request, "registration/thanks.html")


@login_required()
def edit_week(request, year, week, user):
    year, week = correct_week_overflow(year, week)

    entry_id = request.GET.get("entry", None)
    is_special = "True" == request.GET.get("special", "False")
    regular = not is_special

    if entry_id:
        entry = _get_old_entry(entry_id)
    else:
        entry = _make_new_entry(regular, user, week, year)

    form = entry_form_factory(entry)
    return _render_page_with_form(form, request, user, week, year)


def _get_old_entry(entry_id):
    return Entry.objects.get(id=entry_id)


def _make_new_entry(regular, user, week, year):
    year, week = correct_week_overflow(year, week)

    if regular:
        entry = RegularEntry(year=year,
                             week=week,
                             user=User.objects.get(id=user))
    else:
        entry = SpecialEntry(year=year,
                             week=week,
                             user=User.objects.get(id=user))
    return entry


def _render_page_with_form(form: Form, request, user, week, year):
    year, week = correct_week_overflow(year, week)
    regular_entries = RegularEntry.get_entries_of_week(user, year, week)
    special_entries = SpecialEntry.get_entries_of_week(user, year, week)

    systems = serializers.serialize("json", System.objects.all())
    projects = serializers.serialize("json", Project.objects.all())
    tasks = serializers.serialize("json", Task.objects.all())
    activities = serializers.serialize("json", Activity.objects.all())

    user_object = User.objects.get(id=user)
    unfinished_weeks = unfinished_weeks_of_user(user_object)
    shortcuts = entry_shortcuts(user_object, int(year), int(week))
    week_complete = CompletedWeek.objects.filter(
        user=user_object, week=week, year=year).count() > 0

    return render(request,
                  "nhour/index.html",
                  context={'entries': regular_entries,
                           'special_entries': special_entries,
                           'week': week,
                           'user': user_object,
                           'form': form,
                           'regular_entry': isinstance(form, RegularEntryForm),
                           'year': year,
                           'total_hours': _sum_entry_hours(regular_entries,
                                                           special_entries),
                           'systems': systems,
                           'projects': projects,
                           'tasks': tasks,
                           'activities': activities,
                           'shortcuts': shortcuts,
                           'week_complete': week_complete,
                           'unfinished_weeks': sorted(list(unfinished_weeks))})


def _sum_entry_hours(regular_entries, special_entries):

    sum_special = special_entries.aggregate(Sum('hours'))['hours__sum']
    sum_regular = regular_entries.aggregate(Sum('hours'))['hours__sum']

    sum_special = sum_special if sum_special else 0
    sum_regular = sum_regular if sum_regular else 0
    return sum_special + sum_regular


@login_required
def save_entry(request, id):
    entry = Entry.objects.get(id=id)
    form = entry_form_factory(entry, request.POST)
    return _submit_form(request, form)


def _submit_form(request, form):
    if form.is_valid():
        form.save()
        return redirect('edit_week', form.instance.year, form.instance.week,
                        form.instance.user.id)
    else:
        return _render_page_with_form(form, request, form.instance.user.id,
                                      form.instance.week, form.instance.year)


@login_required
def create_entry(request):
    is_special = "True" == request.GET.get("special", "False")
    if is_special:
        form = SpecialEntryForm(request.POST)
    else:
        form = RegularEntryForm(request.POST)
    return _submit_form(request, form)


def _redirect_to_entry_list(entry):
    return redirect(reverse("edit_week",
                            args=[entry.year, entry.week, entry.user.id]))


@login_required()
def delete_entry(request, entry_id):
    deleted_entry = get_object_or_404(Entry, id=entry_id)
    deleted_entry.delete()
    return _redirect_to_entry_list(deleted_entry)


@login_required
def week_complete(request, year, week, user):
    year, week = correct_week_overflow(year, week)
    complete = request.POST.get("complete", 'off')
    user_object = User.objects.get(id=user)
    if complete == 'off':
        _delete_completed_week_if_exists(year, week, user_object)

    if complete == 'on':
        _save_completed_week(year, week, user_object)

    return HttpResponse('Success')


def _save_completed_week(year, week, user):
    year, week = correct_week_overflow(year, week)
    CompletedWeek.objects.get_or_create(year=year, week=week, user=user)


def _delete_completed_week_if_exists(year, week, user):
    year, week = correct_week_overflow(year, week)
    try:
        CompletedWeek.objects.get(year=year, week=week, user=user).delete()
    except:
        pass

nhour/templates/nhour/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load tags %}
<html lang="en">
<head>
    <script src="{% static 'jquery-2.1.4.min.js'%}"></script>
    <script src="{% static 'nouislider/nouislider.js'%}"></script>
    <meta charset="UTF-8">
    <title>Tuutikki</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'pure-min.css' %}">
    <link rel="stylesheet" href="{% static 'nouislider/nouislider.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.5.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'common.css'%}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

</head>
<body>
<div class="pure-menu pure-menu-horizontal" style="background-color: #2196F3; box-shadow: 3px 3px 3px #888888;">
    <ul class="pure-menu-list" style="width: 100%">
        <div class="menu-left">
            <li class="pure-menu-item"><a href="/" style="color: #FFFFFF; " class="pure-menu-heading pure-menu-link"><i class="fa fa-clock-o" aria-hidden="true"></i>
Tuutikki</a></li>
            <li class="pure-menu-item"><a style="color: #FFFFFF; " href="{% caravel_url %}" class="pure-menu-link"><i class="fa fa-bar-chart" aria-hidden="true"></i>
 Statistics</a></li>
            <li class="pure-menu-item"><a style="color: #FFFFFF;" href="/admin"
                                          class="pure-menu-link"><i class="fa fa-cog" aria-hidden="true"></i>

Administration</a>
            </li>
        </div>
        <div class="menu-right">
            {% if not user.is_anonymous %}
            <li class="pure-menu-item"><a style="color: #FFFFFF;" href="{% url 'logout' %}" class="pure-menu-link"> Log
                Out <i class="fa fa-sign-out" aria-hidden="true"></i>
</a>
            </li>
        </div>
        {% endif %}
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

nhour/templates/nhour/entry_edit.html
{% load staticfiles %}
<div class="edit-week-top-bar">
            <div id="new-entry-buttons">
                <a type="button" href="{% url 'edit_week' year week user.id %}"
                   class="pure-button {% if regular_entry %} pure-button-primary-nhour {% endif %} save">Regular</a>
                <a type="button" href="{% url 'edit_week' year week user.id %}?special=True"
                   class="pure-button {% if not regular_entry%} pure-button-primary-nhour {% endif %} save">Special</a>
            </div>
        </div>
{% if not request.GET.special %}
    Shortcuts
    <div class="quick-select" style="width: 100%;">
        {% for s in shortcuts %}
            <button class="pure-button" data-system="{{ s.system.id }}" data-project="{{ s.project.id }}" data-task="{{ s.task.id }}">
                {{ s.system.name }} {% if s.project %} - {{ s.project.name }} {% endif %} - {{ s.task.name }}
            </button>
        {% endfor %}
    </div>
{% endif %}
<form class="pure-form pure-form-stacked" method="post" style="margin-top: 8px;">
    {% csrf_token %}
    <div class="blueback">
        <fieldset>
            <div id="entry-edit-form">
                {% for field in form %}
                <div class="fieldWrapper">
                    {% if not field.is_hidden %}
                    <label for="{{ field.auto_id }}">
                        {{ field.label }}
                        {% if field.field.required %}
                            <span class="required">*</span>
                        {% endif %}
                        {% for error in field.errors %}
                            <span class="required" style="float: right;">{{ error }}</span>
                        {% endfor %}
                    </label>
                    {% endif %}
                    {{ field }}
                    <div class="doc-box blueback blueback-lighter"></div>
                </div>
                {% endfor %}
            </div>
            <label for="slider">Hours: <input type="number" min="0.5" max="40" step="0.5" id="hours-selected"></label>

            <div id="slider"></div>

        </fieldset>
    </div>
    <div class="submit-buttons">
      {% if form.instance.id %}

      <button type="submit" formaction="{% url 'save_entry' form.instance.id %}" class="pure-button save"><i class="fa fa-floppy-o"></i>
          Save
      </button>
      <button type="submit" formaction="{% url 'delete_entry' form.instance.id %}" class="pure-button save"><i class="fa fa-trash"></i>
          Delete
      </button>
      <a type="button" href="{% url 'edit_week' year week user.id %}" class="pure-button save"><i class="fa fa-ban"></i>
          Cancel
      </a>

      {% else %}
      <button type="submit" class="pure-button save" formaction="{% url 'create_entry' %}{% if request.GET.special %}?special={{ request.GET.special }} {% endif %}"><i class="fa fa-plus"></i>
          Add
      </button>
      {% endif %}
    </div>
</form>
<script src="{% static 'ui_slider.js'%}"></script>
<script src="{% static 'docbox.js'%}"></script>
<script>

{% if form.instance.id %}
    defaultHours = {{ form.instance.hours }}
{% else %}
    defaultHours = 10;
{% endif %}
$(document).ready(createSlider(defaultHours));


{% if not request.GET.special %}

    var tasks = {{ tasks | safe}}
    var projects = {{ projects | safe}}
    var systems = {{ systems | safe}}

    new DocBox(tasks, $("#id_task"), $("#id_task").siblings(".doc-box"));
    new DocBox(projects, $("#id_project"), $("#id_project").siblings(".doc-box"));
    new DocBox(systems, $("#id_system"), $("#id_system").siblings(".doc-box"));

{% else %}

    activities = {{ activities | safe }}
    new DocBox(activities, $("#id_activity"), $("#id_activity").siblings(".doc-box"));

{% endif %}

$(".quick-select button").click(function(event) {
    var selected = $(event.target);
    $("#id_system").val(selected.data("system"));
    $("#id_project").val(selected.data("project"));
    $("#id_task").val(selected.data("task"));

    $("#id_system").click();
    $("#id_project").click();
    $("#id_task").click();
});

$("#id_system").change(function(event) {
    var selected = $(event.target);
    var systemId = parseInt(selected.val());

    var relatedProjects = projects.filter(function(p) {
        return p.fields.related_systems.includes(systemId);
    });

    var relatedProjectIds = relatedProjects.map(function(p) {return p.pk})

    $("#id_project option").each(function(index, element) {
       if(index > 0) {
           if(relatedProjectIds.includes(parseInt(element.value))) {
               $(element).show();
           } else {
               $(element).hide();
           }
       }
    });
    $("#id_project").val("");
});

</script>

nhour/templates/nhour/entry_list.html
{% if entries %}
<h2>Regular</h2>
<table class="blueback pure-table entry-list">
    <tr>
        <th style="width: 50px;"><i class="fa fa-clock-o"></i></th>
        <th>System</th>
        <th>Project</th>
        <th>Task</th>
        <th>Comment</th>
    </tr>
    {% for entry in entries %}
    <tr class="blueback blueback-lighter entry-list-row"
        data-url="{% url 'edit_week' year week user.id %}?entry={{ entry.id }}">
        <td><div class="entry-list-cell">{{ entry.hours }}</div></td>
        <td><div class="entry-list-cell">{{ entry.system }}</div></td>
        <td><div class="entry-list-cell">{{ entry.project }}</div></td>
        <td><div class="entry-list-cell">{{ entry.task }}</div></td>
        <td><div class="entry-list-cell">{{ entry.comment }}</div></td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if special_entries %}
<h2>Special</h2>
<table class="blueback pure-table entry-list">
    <tr>
        <th style="width: 10%;"><i class="fa fa-clock-o"></i></th>
        <th>Activity</th>
        <th>Comment</th>
    </tr>
    {% for entry in special_entries %}
    <tr class="blueback blueback-lighter entry-list-row"
        data-url="{% url 'edit_week' year week user.id %}?entry={{ entry.id }}">
        <td><div class="entry-list-cell">{{ entry.hours }}</div></td>
        <td><div class="entry-list-cell">{{ entry.activity }}</div></td>
        <td><div class="entry-list-cell">{{ entry.comment }}</div></td>
    </tr>
    {% endfor %}
</table>
{% endif %}
<script>
    $(".entry-list-row").click(
        function(click) {
            edit_url = $(click.delegateTarget).data("url")
            window.location.assign(edit_url);
        }
    )
</script>

nhour/templates/nhour/index.html
{% extends 'nhour/base.html' %}
{% load tags %}
{% block content %}
<div class="">
    <div id="container">
        {% if unfinished_weeks %} 
            <span class="required">You have previous unfinished weeks!</span>
            {% for week in unfinished_weeks %}
              <a href="{% url 'edit_week' week.0 week.1 user.id %}" class="unfinished-week-link">{{ week.0 }} - {{ week.1}}</a>
            {% endfor %}
        <br>
        {% endif %}
        <div class="week-selector">
            {% week_start_date year week%} — {% week_end_date year week%}
        </div>
        <div class="week-difference">
            {% filter add_plus_if_not_negative %} {% week_difference_today year week%} {% endfilter %}
            <a href={% previous_week_url year week user.id %}>Previous</a>
            <a href={% next_week_url year week user.id %}>Next</a>
        </div>
        
        <h2 style="margin-bottom: 2px;">{{ user.first_name }} {{ user.last_name }}</h2>
        <div>
            {% if total_hours %} Total: {{ total_hours }} {% endif %}
             <form id="complete-form" class="pure-form">
                 {% csrf_token %}
                 <label for="complete">This week is complete</label>
                 <input id="complete" name="complete" type="checkbox" {% if week_complete %} checked {% endif %}>
                 <span id="post-success" style="color: green; font-size: 80%; display: none;"> Saved successfully!</span>
            </form>
        </div>

        {% include 'entry_edit.html'%}
        {% include 'entry_list.html' %}
    </div>
</div>
<script>
    $("#complete").change(function(event) {
        console.log($("#complete-form").serialize())
        $.post(
         "{% url 'complete' year week user.id %}",
         $("#complete-form").serialize(),
         function() {
            $("#post-success").hide()
            $("#post-success").delay(50).show()
            $("#post-success").delay(500).fadeOut('fast')
         })
         .error(function() {alert("Could not change completion status, please try again later!")});
    });
</script>
{% endblock %}